import React, { useState } from 'react';
import { FileSignature, Sparkles, Loader2, Copy, Check, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { motion, AnimatePresence } from 'motion/react';
import { generateLegalDocument, ProjectLanguage } from '@/lib/gemini';
import { cn } from '@/lib/utils';
import { jsPDF } from 'jspdf';

export function DocumentGenerator({ language }: { language: ProjectLanguage }) {
  const [docType, setDocType] = useState('NDA');
  const [description, setDescription] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const t = {
    es: {
      title: "Generador Profesional",
      subtitle: "Drafting de Documentos mediante IA Avanzada",
      typeLabel: "Tipo de Documento",
      reqLabel: "Requerimientos Específicos",
      placeholder: "Ej: NDA mutuo, periodo de 2 años, enfoque en IP de software...",
      generate: "GENERAR DRAFT",
      generating: "DRAFTING...",
      result: "/ RESULTADO",
      resultSub: "Documento Generado",
      copy: "COPIAR TEXTO",
      copied: "COPIADO!",
      download: "PDF",
      headerInfo: "GENERADO POR AUDITORÍA LEGAL IA - DRAFT PROFESIONAL",
      footerInfo: "Propia Solución Professional"
    },
    en: {
      title: "Professional Generator",
      subtitle: "Document Drafting via Advanced AI",
      typeLabel: "Document Type",
      reqLabel: "Specific Requirements",
      placeholder: "e.g. Mutual NDA, 2-year period, focus on software IP...",
      generate: "GENERATE DRAFT",
      generating: "DRAFTING...",
      result: "/ RESULT",
      resultSub: "Generated Document",
      copy: "COPY TEXT",
      copied: "COPIED!",
      download: "PDF",
      headerInfo: "GENERATED BY AI LEGAL AUDIT - PROFESSIONAL DRAFT",
      footerInfo: "Propia Solución Professional"
    }
  }[language];

  const types = [
    { id: 'NDA', label: language === 'es' ? 'Acuerdo de Confidencialidad' : 'Non-Disclosure Agreement' },
    { id: 'Service Agreement', label: language === 'es' ? 'Contrato de Servicios' : 'Service Agreement' },
    { id: 'Employment Contract', label: language === 'es' ? 'Contrato Laboral' : 'Employment Contract' },
    { id: 'Privacy Policy', label: language === 'es' ? 'Política de Privacidad' : 'Privacy Policy' },
    { id: 'Terms of Service', label: language === 'es' ? 'Términos de Servicio' : 'Terms of Service' },
  ];

  const handleGenerate = async () => {
    if (!description) return;
    setIsGenerating(true);
    try {
      const result = await generateLegalDocument(docType, description, language);
      setOutput(result);
    } catch (error) {
      console.error('Failed to generate:', error);
      alert('Generation failed.');
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    let y = 20;
    
    // Professional Header
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(docType.toUpperCase(), 20, 25);
    
    doc.setTextColor(255, 215, 0);
    doc.setFontSize(8);
    doc.text("GENERADO POR AUDITORÍA LEGAL IA - DRAFT PROFESIONAL", 20, 32);

    y = 55;
    
    const rawLines = output.split('\n');
    
    rawLines.forEach((line) => {
      let isHeader = false;
      let headerLevel = 0;
      
      let cleanLine = line.trim();

      if (cleanLine.startsWith('# ')) { isHeader = true; headerLevel = 1; cleanLine = cleanLine.substring(2); }
      else if (cleanLine.startsWith('## ')) { isHeader = true; headerLevel = 2; cleanLine = cleanLine.substring(3); }
      else if (cleanLine.startsWith('### ')) { isHeader = true; headerLevel = 3; cleanLine = cleanLine.substring(4); }
      
      if (!cleanLine) {
        y += 4;
        return;
      }

      if (isHeader) {
        y += 8;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(headerLevel === 1 ? 16 : headerLevel === 2 ? 14 : 12);
        doc.setTextColor(0, 0, 0);
      } else {
        doc.setTextColor(60, 60, 60);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
      }

      if (cleanLine.includes('**')) {
        doc.setFont("helvetica", "bold");
        cleanLine = cleanLine.replace(/\*\*/g, '');
      }

      const splitLines = doc.splitTextToSize(cleanLine, isHeader ? 170 : 165);
      
      splitLines.forEach((sl: string) => {
        if (y > 275) {
          doc.addPage();
          y = 25;
        }
        doc.text(sl, 20, y);
        y += isHeader ? 8 : 6;
      });

      y += 2;
    });

    const pageCount = doc.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setTextColor(200, 200, 200);
        doc.setFontSize(8);
        doc.text(`Propia Solución Professional - Página ${i} de ${pageCount}`, 105, 290, { align: 'center' });
    }

    doc.save(`${docType.toLowerCase()}-${new Date().getTime()}.pdf`);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-12">
      <section className="legal-card p-10 space-y-10 bg-white">
        <div className="flex items-center gap-4 border-b-[3px] border-black pb-6">
          <span className="text-8xl font-black leading-none text-black">Aİ</span>
          <div className="flex flex-col">
            <h2 className="text-4xl font-black uppercase tracking-tighter leading-none">
              {t.title}
            </h2>
            <p className="text-sm font-bold uppercase tracking-widest text-black/40 mt-1">
              {t.subtitle}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
          <div className="space-y-6">
            <label className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-black/40">
              <span className="w-2 h-2 bg-black"></span>
              {t.typeLabel}
            </label>
            <div className="grid grid-cols-1 gap-3">
              {types.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setDocType(t.id)}
                  className={cn(
                    "px-6 py-4 text-left transition-all text-xl font-black italic border-[3px]",
                    docType === t.id 
                      ? "bg-brand-yellow text-black border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] translate-x-[-2px] translate-y-[-2px]" 
                      : "bg-white border-black/10 text-black/30 hover:text-black hover:border-black/40"
                  )}
                >
                  {t.label.toUpperCase()}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-6">
            <label className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.2em] text-black/40">
              <span className="w-2 h-2 bg-black"></span>
              {t.reqLabel}
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder={t.placeholder}
              className="w-full h-56 p-6 bg-slate-50 border-[3px] border-black rounded-none focus:bg-brand-yellow/5 outline-none transition-all text-lg font-bold placeholder:opacity-20"
            />
            <button
              onClick={handleGenerate}
              disabled={!description || isGenerating}
              className="brutalist-button w-full flex items-center justify-center gap-3 disabled:opacity-20"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-6 h-6 animate-spin" />
                  <span>{t.generating}</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-6 h-6" />
                  <span className="text-xl">{t.generate}</span>
                </>
              )}
            </button>
          </div>
        </div>
      </section>

      <AnimatePresence>
        {output && (
          <motion.div
            initial={{ opacity: 0, y: 100 }}
            animate={{ opacity: 1, y: 0 }}
            className="legal-card"
          >
            <div className="bg-black text-white px-8 py-6 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <span className="text-3xl font-black text-brand-yellow">{t.result}</span>
                <h3 className="text-xs font-black uppercase tracking-[0.3em]">{t.resultSub}</h3>
              </div>
              <div className="flex gap-2">
                <button 
                  onClick={downloadPDF}
                  className="px-6 py-2 bg-brand-yellow text-black font-black uppercase text-[10px] tracking-widest hover:bg-white transition-colors brutalist-border flex items-center gap-2"
                >
                  <Download className="w-3 h-3" />
                  {t.download}
                </button>
                <button 
                  onClick={copyToClipboard}
                  className="px-6 py-2 bg-black text-white font-black uppercase text-[10px] tracking-widest hover:bg-brand-yellow hover:text-black transition-colors brutalist-border"
                >
                  {copied ? t.copied : t.copy}
                </button>
              </div>
            </div>
            <div className="p-16 markdown-body bg-white min-h-[800px] font-serif border-t-[3px] border-black text-black">
              <ReactMarkdown>{output}</ReactMarkdown>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
